spring:
  profiles:
    active: vault,${ENV:local}
  cloud:
    config:
      server:
         vault:
          backend: secret
          default-key: application #公共配置属性，所有应用共享
          host: localhost
          port: 8200
          scheme: http
          kv-version: 2
          timeout: 5
          skip-ssl-validation: true
