spring:
  profiles:
    active: ${ENV:local}
  application:
    name: service-discover
server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false
    register-with-eureka: true
  server:
    wait-time-in-ms-when-sync-empty: 0
---
spring:
  profiles: uat
server:
  port: 8763
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8762/eureka/
    fetch-registry: false
    register-with-eureka: true
  server:
    wait-time-in-ms-when-sync-empty: 0
---
spring:
  profiles: dev
server:
  port: 8762
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8763/eureka/
    fetch-registry: false
    register-with-eureka: true
  server:
    wait-time-in-ms-when-sync-empty: 0

