# 默认local是单服务方式
spring:
  profiles:
    active: ${ENV:local}
  application:
    name: service-discover
---
spring:
  profiles: local #本地环境
  freemarker:
    prefer-file-system-access: false
    template-loader-path: classpath:/templates/ #存在BUG，访问不了对应html文件，待解决
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    fetch-registry: false
    register-with-eureka: false #false为单节点
  server:
    wait-time-in-ms-when-sync-empty: 0
---
spring:
  profiles: qa #测试环境
server:
  port: 8763
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8762/eureka/
    fetch-registry: false
    register-with-eureka: true
  server:
    wait-time-in-ms-when-sync-empty: 0
---
spring:
  profiles: dev #开发环境
server:
  port: 8762
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    fetch-registry: false
    register-with-eureka: true
  server:
    wait-time-in-ms-when-sync-empty: 0
