spring:
  application:
    name: service-gateway
  profiles:
    active: ${ENV:local}

server:
  port: 8093

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

zuul:
  ignoredServices: '*'
  routes:
    service-demo2: /v2/**
    service-demo1: /v1/**

