server:
  port: 8881

logging:
  level:
    org.springframework.cloud: 'DEBUG'

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/remote/, file:./, file:./remote/
          add-label-locations: true
          version: 0.1.0
      name: configServer
  application:
    name: config-server

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:8761/eureka/


