spring:
  application:
    name: service-demo2
  profiles:
    active: ${ENV:local}

server:
  port: 8092

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/


